version: '3.8'
services: 
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/defualt.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8.2-fpm
    volumes: 
      - ./html:/usr/share/nginx/html